image: gitpod/workspace-full

tasks:
  - name: Get dependencies
    before: |
      brew install go-task/tap/go-task
      go install github.com/spf13/cobra-cli@latest
    init: task get

vscode:
  extensions:
    - premparihar.gotestexplorer
