# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "Run task build to build the project"
    silent: true
  get:
    cmds:
      - go get -x -t
  build:
    cmds:
      - go build -v
